const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.custom,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Camera3D,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.custom.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.custom.Acts.Accelerate,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{TiledBackground: 0},
	{Block: 0},
	{Sine: 0},
	{CustomMovement: 0},
	{Player: 0},
	{Touch: 0},
	{Keyboard: 0},
	{DistanceDisplay: 0},
	{TopSpawner: 0},
	{BottomSpawner: 0},
	{Car: 0},
	{"3DCamera": 0},
	{Audio: 0},
	{wallblock: 0},
	{Button: 0},
	{TiledBackground2: 0},
	{TotalDistance: 0},
	{NextBlockX: 0},
	{TopSpawnerTargetY: 0},
	{BottomSpawnerTargetY: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Block: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	DistanceDisplay: class extends self.ITextInstance {},
	TopSpawner: class extends self.ISpriteInstance {},
	BottomSpawner: class extends self.ISpriteInstance {},
	Car: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	wallblock: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {}
}